### ISSUE TITLE
Fix migration version validation

### ISSUE THREAD

**Issue by DevCorvette** [SIIS-Ltd/Curiosity.Migrations#22]
Version validator must throw validation error when a version match `20210916-1055-00`

**Comment by Markeli** [comment]
This is a valid version for Curiosity.Migrations. Symbol `-` is used for logically separating numbers in the major part of a version. At SIIS we decided to use DateTime format `yyyyMMdd-HHmm` as a version. But `yyyy-MM-dd-HHmm` is also a valid version format.  

Do we really think that we need to make the version format more strict?

**Comment by Markeli** [comment]
Fixed at `v4.0.0`. Replaced `-` by `-` as separator at version's major part.
